name: java-springboot
displayName: Spring Boot® Atarazana
description: Spring Boot® using Java - Atarazana
tags: ["Java", "Spring"]
globalMemoryLimit: 2674Mi
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
projectType: "spring"
language: "java"
